//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ppe3_desktop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class connexionBase : DbContext
    {
        public connexionBase()
            : base("name=connexionBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<emprunt> emprunt { get; set; }
        public virtual DbSet<episode> episode { get; set; }
        public virtual DbSet<film> film { get; set; }
        public virtual DbSet<genre> genre { get; set; }
        public virtual DbSet<saison> saison { get; set; }
        public virtual DbSet<serie> serie { get; set; }
        public virtual DbSet<support> support { get; set; }
    }
}
